### ISSUE TITLE
Right click menu for selected states

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#138]
The issue is a former Milestone. As long as this is not appropriate it is converted to an issue.

If a state is selected in the state machine tree widget or graphical editor and clicked with the right mouse button a menu with several option should be open. 
This will support access to features like (which may are still open issues):
- [x] Copy
- [x] Paste
- [x] Run (start from this state, run to this state)
- [x] Save as state machine (single state) #88
- [x] Group/Un-Group states (multiple states) #49
- [x] Substitute (state with library) #119

As long as some of the features are not implemented yet the issue depend on those.

The issue may gets extended by more useful right-click features.

Originally created by @Rbelder  at 2016-07-13 08:58:56+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
first implementation can be found in the develop branch, see commit d5e09024.


Originally created by @Rbelder  at 2016-07-15 14:55:45+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
By finishing the Core implementation of "state substitution", see #119, this issue is solved.


Originally created by @Rbelder  at 2016-08-04 15:15:43+00:00 (moved from RMC internal repository)
