### ISSUE TITLE
Gaphas meta data update and scaling not fully working for group/ungroup/substitute state(s)

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#158]
The issue combines problem with meta data scaling or update when doing a group states, ungroup state or substitute state action. The sub-tasks concern smaller elements to be fixed to improve usability and maybe also features that are not implemented for opengl.
- [x] scaling and relative position changes of group states and ungroup state actions should work simular to opengl
- [x] suspend drawing meta data for all three actions similar to state type change
- [x] the right usage of the meta_signal of the state model to inform the gaphas viewer about changes made by the model has to be found, too. At the moment, the signal creates problems with the modification history.

Fill free to add some sub-task concerning this three actions. :smile: 

Originally created by @Rbelder  at 2016-08-11 10:17:49+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
After close to have fixed issue #291 and now seeing this old issue I think sub-task 1 and 3 are covered by issue #291. 

@franzlst Because of this the question is it suitable to suspend the actions of gaphas while group, un-group and substitute like for change_state_type? My first try to do this were not working. 


Originally created by @Rbelder  at 2017-02-24 18:43:55+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
After the merge of refactor_complex_action branch, thereby the introduction of the action-signal and the encapsulation of complex actions by the before and after signal this issue is considered to be solved. The suspending of drawing is handled by the gaphas editor by observing respective action-signal.
As long as it is bug issue it needs a reliable test. So we should not lose track of this.

If there is any problem with this features and its meta data in gaphas consider to reopen the issue.

Originally created by @Rbelder  at 2017-06-07 15:08:18+00:00 (moved from RMC internal repository)
