### ISSUE TITLE
Gaphas: Group/Ungroup/Substitute results in not fully viewed and notified changes of meta data

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#291]
Gaphas viewing and the meta-data in the model are not identical. This issue is for the cases that 
- [x] states are grouped
- [x] a state is ungrouped
- [x] a state is substituted
  The changes are not viewed in the way the meta-data parameter are set in the model meta data dictionary.

**Reproduction:**
- create a new state machine
- add a state or multiple ones (arbitrary state or a library state) (may set the added state as start state, to easily find the state after the next action)
- Group/Ungroup/Substitute the state

The states are not situated as in the meta data, what can be easily seen if you undo and redo the action with the modification history or you store the resulting state machine directly and reload it.

This issue is similar to #174 and should be insert as test scenarios into the test environment of issue #175.

The issue is labeled as part of the OpenSource milestone. I also would prefer to label #175 to be part of this milestone again, because of the importance of Gaphas testing for the usability of RAFCON.

Originally created by @Rbelder  at 2017-02-16 13:06:19+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
The issue seems close to fixed. 

At the moment "substitute library state as template" is not doing the re-sized of the new state (so the full library) to the size of the previous state.

The notification to gaphas and the modification history seems fine. 

So only some tuning of the re-size is needed and I hope we formalize the re-size of state while this without hiding this in gaphas.


Originally created by @Rbelder  at 2017-02-24 18:50:55+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
After the merge of refactor_complex_action branch, thereby the introduction of the action-signal and the encapsulation of complex actions by the before and after signal this issue is considered to be solved. 
As long as it is bug issue it needs a reliable test. So we should not lose track of this.

If there is any problem with this features and its meta data in gaphas consider to reopen the issue.

Originally created by @Rbelder  at 2017-06-07 15:06:55+00:00 (moved from RMC internal repository)
