### ISSUE TITLE
copy and past meta data of states

### ISSUE THREAD

**Issue by franzlst** [DLR-RM/RAFCON#540]
The ability to copy the format of a state (esp. size) would help to have nicely formatted states inside one hierarchy level.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2018-05-29 05:17:36+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
Yeah that would be like a format copy in a text editor like LibreOffice or Word. Nice thing. We could simple put it on `strg-shift-c` and `strg-shift-v`.

Implementation should be very easy but the expected behavior can divert:
* [ ] in case of a port the position has to be copied
* [ ] in case of a state it size and it port relative positions to be able to use it more generic
* [ ] only support of 1 to 1 or 1 to n meta data copy actions

That are the User-Features which I would start with and see how useful it becomes and where to place menu-items.
* [ ] in the menu-bar
* [ ] in the right click menu in the state machine editor and the state machine tree (in both to give the user a better hand to use it the first time (with short-cut on the menu-item))

Originally created by @Rbelder  at 2018-05-30 13:49:23+00:00 (moved from RMC internal repository)

**Comment by franzlst** [comment]
This issue was upvoted by @mjschuster two weeks ago.

Originally created by @sebastian-brunner  (Sebastian.Brunner@dlr.de) at 2019-08-19 06:43:58+00:00 (moved from RMC internal repository)
